import { converter } from 'culori';
import { beforeAll, describe, expect, it } from 'vitest';
import { colordx, extend } from '../src/index.js';
import a98Plugin from '../src/plugins/a98rgb.js';
import prophotoPlugin from '../src/plugins/prophoto.js';

// Fully deterministic (no RNG) cross-check of the a98 / prophoto conversions against culori
// over a dense sRGB grid. Two independent guarantees:
//   1. Forward sRGB → space channels match culori within the 4-decimal storage rounding bound.
//   2. Every grid color round-trips losslessly: sRGB → color(...) string → identical sRGB byte.
// Because the grid is generated by fixed nested loops, the exact same colors run every time.

const culoriToA98 = converter('a98');
const culoriToProphoto = converter('prophoto');

// Every sRGB channel 0..255 stepped by 15 (plus 255) → 18^3 = 5832 colors.
const STEPS: number[] = [];
for (let v = 0; v <= 255; v += 15) STEPS.push(v);
if (STEPS[STEPS.length - 1] !== 255) STEPS.push(255);

// toA98()/toProphoto() round channels to 4 dp; the largest possible deviation from culori's
// full-precision value is half a unit in the last place = 5e-5 (plus a hair of FP slack).
const ROUND_BOUND = 5.1e-5;

interface GridResult {
  count: number;
  fwdA98: number;
  fwdPp: number;
  rtA98Fails: number;
  rtPpFails: number;
}

let result: GridResult;

beforeAll(() => {
  extend([a98Plugin, prophotoPlugin]);
  let fwdA98 = 0,
    fwdPp = 0,
    rtA98Fails = 0,
    rtPpFails = 0,
    count = 0;

  for (const r of STEPS)
    for (const g of STEPS)
      for (const b of STEPS) {
        count++;
        const hex = '#' + [r, g, b].map((x) => x.toString(16).padStart(2, '0')).join('');
        const cx = colordx(hex);
        const cuBase = { mode: 'rgb' as const, r: r / 255, g: g / 255, b: b / 255 };

        const a = (cx as unknown as { toA98(): { r: number; g: number; b: number } }).toA98();
        const cuA = culoriToA98(cuBase)!;
        fwdA98 = Math.max(fwdA98, Math.abs(a.r - (cuA.r ?? 0)), Math.abs(a.g - (cuA.g ?? 0)), Math.abs(a.b - (cuA.b ?? 0)));

        const p = (cx as unknown as { toProphoto(): { r: number; g: number; b: number } }).toProphoto();
        const cuP = culoriToProphoto(cuBase)!;
        fwdPp = Math.max(fwdPp, Math.abs(p.r - (cuP.r ?? 0)), Math.abs(p.g - (cuP.g ?? 0)), Math.abs(p.b - (cuP.b ?? 0)));

        const a98Str = (cx as unknown as { toA98String(): string }).toA98String();
        if (colordx(a98Str).toHex() !== hex) rtA98Fails++;
        const ppStr = (cx as unknown as { toProphotoString(): string }).toProphotoString();
        if (colordx(ppStr).toHex() !== hex) rtPpFails++;
      }

  result = { count, fwdA98, fwdPp, rtA98Fails, rtPpFails };
});

describe('a98 / prophoto — deterministic grid cross-check vs culori', () => {
  it('covers the full 18³ grid', () => {
    expect(result.count).toBe(STEPS.length ** 3);
  });

  it('sRGB → a98 matches culori within the 4-decimal rounding bound', () => {
    expect(result.fwdA98).toBeLessThanOrEqual(ROUND_BOUND);
  });

  it('sRGB → prophoto matches culori within the 4-decimal rounding bound', () => {
    expect(result.fwdPp).toBeLessThanOrEqual(ROUND_BOUND);
  });

  it('every color round-trips losslessly through the a98 string', () => {
    expect(result.rtA98Fails).toBe(0);
  });

  it('every color round-trips losslessly through the prophoto string', () => {
    expect(result.rtPpFails).toBe(0);
  });
});
