name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - name: Enable Corepack
        run: corepack enable

      - name: Cache yarn global cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - run: yarn install --immutable

      - run: yarn build
      - run: yarn publint

      - uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          title: "chore: release"
          commit: "chore: release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
